/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import '@cuuats/webmapgl';


export namespace Components {

  interface LrtpAddressSearch {
    'bbox': [number, number, number, number];
    'forwardGeocodeUrl': string;
    'jobId': string;
    'limit': number;
  }
  interface LrtpAddressSearchAttributes extends StencilHTMLAttributes {
    'bbox'?: [number, number, number, number];
    'forwardGeocodeUrl'?: string;
    'jobId'?: string;
    'limit'?: number;
  }

  interface LrtpApp {
    'bbox': string;
    'commentUrl': string;
    'forwardGeocodeUrl': string;
    'likeUrl': string;
    'multiuser': boolean;
    'schemaUrl': string;
    'styleUrl': string;
    'surveyUrl': string;
    'token': string;
  }
  interface LrtpAppAttributes extends StencilHTMLAttributes {
    'bbox'?: string;
    'commentUrl'?: string;
    'forwardGeocodeUrl'?: string;
    'likeUrl'?: string;
    'multiuser'?: boolean;
    'schemaUrl'?: string;
    'styleUrl'?: string;
    'surveyUrl'?: string;
    'token'?: string;
  }

  interface LrtpCommentDetail {
    'feature': any;
    'likeUrl': string;
    'token': string;
  }
  interface LrtpCommentDetailAttributes extends StencilHTMLAttributes {
    'feature'?: any;
    'likeUrl'?: string;
    'token'?: string;
  }

  interface LrtpSurveyController {
    'commentThreshold': number;
    'create': () => Promise<HTMLIonAlertElement>;
    'delay': number;
    'likeThreshold': number;
  }
  interface LrtpSurveyControllerAttributes extends StencilHTMLAttributes {
    'commentThreshold'?: number;
    'delay'?: number;
    'likeThreshold'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'LrtpAddressSearch': Components.LrtpAddressSearch;
    'LrtpApp': Components.LrtpApp;
    'LrtpCommentDetail': Components.LrtpCommentDetail;
    'LrtpSurveyController': Components.LrtpSurveyController;
  }

  interface StencilIntrinsicElements {
    'lrtp-address-search': Components.LrtpAddressSearchAttributes;
    'lrtp-app': Components.LrtpAppAttributes;
    'lrtp-comment-detail': Components.LrtpCommentDetailAttributes;
    'lrtp-survey-controller': Components.LrtpSurveyControllerAttributes;
  }


  interface HTMLLrtpAddressSearchElement extends Components.LrtpAddressSearch, HTMLStencilElement {}
  var HTMLLrtpAddressSearchElement: {
    prototype: HTMLLrtpAddressSearchElement;
    new (): HTMLLrtpAddressSearchElement;
  };

  interface HTMLLrtpAppElement extends Components.LrtpApp, HTMLStencilElement {}
  var HTMLLrtpAppElement: {
    prototype: HTMLLrtpAppElement;
    new (): HTMLLrtpAppElement;
  };

  interface HTMLLrtpCommentDetailElement extends Components.LrtpCommentDetail, HTMLStencilElement {}
  var HTMLLrtpCommentDetailElement: {
    prototype: HTMLLrtpCommentDetailElement;
    new (): HTMLLrtpCommentDetailElement;
  };

  interface HTMLLrtpSurveyControllerElement extends Components.LrtpSurveyController, HTMLStencilElement {}
  var HTMLLrtpSurveyControllerElement: {
    prototype: HTMLLrtpSurveyControllerElement;
    new (): HTMLLrtpSurveyControllerElement;
  };

  interface HTMLElementTagNameMap {
    'lrtp-address-search': HTMLLrtpAddressSearchElement
    'lrtp-app': HTMLLrtpAppElement
    'lrtp-comment-detail': HTMLLrtpCommentDetailElement
    'lrtp-survey-controller': HTMLLrtpSurveyControllerElement
  }

  interface ElementTagNameMap {
    'lrtp-address-search': HTMLLrtpAddressSearchElement;
    'lrtp-app': HTMLLrtpAppElement;
    'lrtp-comment-detail': HTMLLrtpCommentDetailElement;
    'lrtp-survey-controller': HTMLLrtpSurveyControllerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
